name: lorrence_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  get_storage: ^2.0.3
  ots: ^1.0.0
  video_player: ^2.2.11
  shimmer: ^2.0.0
  get: 4.6.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
